name: haskell-mcp-server
version: 0.1.0.0
github: "username/haskell-mcp-server"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2025 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
synopsis: A Model Context Protocol server implementation in Haskell
category: Network

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/username/haskell-mcp-server#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson >= 2.0
  - text >= 1.2
  - bytestring >= 0.10
  - websockets >= 0.12
  - network >= 3.1
  - stm >= 2.5
  - containers >= 0.6
  - uuid >= 1.3
  - time >= 1.9
  - mtl >= 2.2
  - transformers >= 0.5
  - async >= 2.2
  - wai >= 3.2
  - wai-websockets >= 3.0
  - warp >= 3.3
  - http-types >= 0.12
  - case-insensitive >= 1.2
  - random >= 1.2
  - base64-bytestring >= 1.0

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskell-mcp-server-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-mcp-server

tests:
  haskell-mcp-server-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-mcp-server
      - hspec
